# Generated by Django 6.0.3 on 2026-04-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquote',
            name='has_video',
            field=models.BooleanField(default=False, help_text='True when the user uploaded an acceptance/condition video.'),
        ),
        migrations.AddField(
            model_name='aiquote',
            name='quote_accepted_by_admin',
            field=models.BooleanField(default=False, help_text='Set when an admin has reviewed the video and accepted the buy-back offer.'),
        ),
        migrations.AddField(
            model_name='aiquote',
            name='quote_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiquote',
            name='video_path',
            field=models.CharField(blank=True, help_text='Object path in Supabase Storage (quote-videos bucket).', max_length=1024),
        ),
    ]
