# Generated by Django 6.0.3 on 2026-04-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quote_video_and_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquote',
            name='booking_link',
            field=models.URLField(blank=True, help_text='Microsoft Booking link submitted by the user.', max_length=1024),
        ),
        migrations.AddField(
            model_name='aiquote',
            name='picked_up',
            field=models.BooleanField(default=False, help_text='Set when an admin marks the item as physically picked up.'),
        ),
        migrations.AddField(
            model_name='aiquote',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
