# Generated by Django 6.0.3 on 2026-04-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aiquote_booking_initiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquote',
            name='assigned_admin_name',
            field=models.CharField(blank=True, help_text='Admin team member currently handling this item.', max_length=120),
        ),
        migrations.AddField(
            model_name='aiquote',
            name='pickup_label_color',
            field=models.CharField(blank=True, help_text='Physical tag color used after pickup (org inventory convention).', max_length=32),
        ),
        migrations.AddField(
            model_name='aiquote',
            name='pickup_label_number',
            field=models.PositiveIntegerField(blank=True, help_text='Physical tag number used after pickup (org inventory convention).', null=True),
        ),
    ]
