# Generated by Django 6.0.3 on 2026-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aiquote_assigned_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquote',
            name='has_video',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the user uploaded an acceptance/condition video.'),
        ),
        migrations.AlterField(
            model_name='aiquote',
            name='picked_up',
            field=models.BooleanField(db_index=True, default=False, help_text='Set when an admin marks the item as physically picked up.'),
        ),
        migrations.AlterField(
            model_name='aiquote',
            name='quote_accepted_by_admin',
            field=models.BooleanField(db_index=True, default=False, help_text='Set when an admin has reviewed the video and accepted the buy-back offer.'),
        ),
    ]
