# Generated by Django 6.0.3 on 2026-07-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_listing_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='msrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original retail price, for showing a percent-off discount. Leave blank if unknown.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='msrp_url',
            field=models.URLField(blank=True, help_text="Link to where the MSRP was sourced (e.g. the product's retail page), shown to buyers.", max_length=1024),
        ),
    ]
