"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file if it exists
env_path = BASE_DIR / '.env'
if env_path.exists():
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                key, value = line.split('=', 1)
                os.environ.setdefault(key, value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    print("Secret key not initialized")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
VERCEL_ANALYTICS_ENABLED = os.environ.get('VERCEL_ANALYTICS_ENABLED', 'False') == 'True'

default_allowed_hosts = [
    'sharebear.app',
    'www.sharebear.app',
    'baylorshare.com',
    'www.baylorshare.com',
]
if DEBUG:
    default_allowed_hosts.extend(['localhost', '127.0.0.1'])

env_allowed_hosts = os.environ.get('ALLOWED_HOSTS')
if env_allowed_hosts:
    ALLOWED_HOSTS = [host.strip() for host in env_allowed_hosts.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = default_allowed_hosts


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'core',  # utils, models
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


def build_default_database_config():
    database_url = os.environ.get('DATABASE_URL')
    if not database_url:
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    parsed = urlparse(database_url)
    if parsed.scheme not in {'postgres', 'postgresql'}:
        raise ValueError('DATABASE_URL must start with postgres:// or postgresql://')

    query_params = parse_qs(parsed.query)
    options = {key: values[-1] for key, values in query_params.items() if values}
    options.setdefault('sslmode', 'require')

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': parsed.path.lstrip('/') or 'postgres',
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or 5432),
        'OPTIONS': options,
    }


DATABASES = {'default': build_default_database_config()}

running_tests = len(sys.argv) > 1 and sys.argv[1] == 'test'
use_postgres_for_tests = os.environ.get('USE_POSTGRES_FOR_TESTS', 'False') == 'True'
if running_tests and DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql' and not use_postgres_for_tests:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
WHITENOISE_USE_FINDERS = os.environ.get('VERCEL', '') == '1'

use_manifest_static_storage = os.environ.get('USE_MANIFEST_STATIC_STORAGE', 'False') == 'True'
staticfiles_storage_backend = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
    if use_manifest_static_storage
    else 'whitenoise.storage.CompressedStaticFilesStorage'
)

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': staticfiles_storage_backend,
    },
}

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Google Gemini (AI Quote)
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '') or None
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-2.0-flash')

# Supabase Storage (quote condition videos) — set SUPABASE_URL and service role in production.
# Create bucket `quote-videos` (private) in the Supabase dashboard; uploads use the service role key.
SUPABASE_URL = (os.environ.get('SUPABASE_URL', '') or '').rstrip('/')
SUPABASE_SERVICE_ROLE_KEY = os.environ.get('SUPABASE_SERVICE_ROLE_KEY', '') or None
SUPABASE_QUOTE_VIDEOS_BUCKET = os.environ.get('SUPABASE_QUOTE_VIDEOS_BUCKET', 'quote-videos')

# Google Calendar (pickup: preset weekly slots in app, events.insert on book; service account)
# Share the destination calendar with the service account; enable Calendar API in GCP.
def _env_csv(name: str) -> list[str]:
    raw = (os.environ.get(name) or '').strip()
    if not raw:
        return []
    return [p.strip() for p in raw.split(',') if p.strip()]


def _load_pickup_weekly_slots() -> list[dict]:
    """
    Weekly recurring pickup windows. weekday: 0=Monday ... 6=Sunday (Python date.weekday()).

    - Single slot: {"weekday": int, "start": "HH:MM", "end": "HH:MM"}.
    - Hourly slots: {"weekday": int, "hourly": true, "first": "HH:MM", "last_start": "HH:MM"}
      — one 1-hour block per hour from first through last_start (inclusive), e.g. 9–10 … 17–18.
    """
    raw = (os.environ.get('PICKUP_WEEKLY_SLOTS_JSON') or '').strip()
    if raw:
        import json

        try:
            data = json.loads(raw)
            if isinstance(data, list) and data:
                return data
        except json.JSONDecodeError:
            pass
    # Default: Fri & Sat 9am–5pm hourly; Sun 12pm–5pm hourly (local GOOGLE_PICKUP_TIMEZONE)
    return [
        {'weekday': 4, 'hourly': True, 'first': '09:00', 'last_start': '17:00'},
        {'weekday': 5, 'hourly': True, 'first': '09:00', 'last_start': '17:00'},
        {'weekday': 6, 'hourly': True, 'first': '12:00', 'last_start': '17:00'},
    ]


GOOGLE_SERVICE_ACCOUNT_KEY_PATH = (os.environ.get('GOOGLE_SERVICE_ACCOUNT_KEY_PATH') or '').strip() or None
# Preferred on Vercel/serverless: full service-account JSON string (not a filesystem path).
GOOGLE_SERVICE_ACCOUNT_KEY_JSON = (os.environ.get('GOOGLE_SERVICE_ACCOUNT_KEY_JSON') or '').strip() or None
# Comma-separated calendar ID where new pickup events are created (e.g. sharebearhelp@gmail.com)
GOOGLE_SLOT_SOURCE_CALENDAR_IDS = _env_csv('GOOGLE_SLOT_SOURCE_CALENDAR_IDS')
GOOGLE_PICKUP_SLOT_DAYS_AHEAD = int(os.environ.get('GOOGLE_PICKUP_SLOT_DAYS_AHEAD', '30'))
GOOGLE_PICKUP_TIMEZONE = (os.environ.get('GOOGLE_PICKUP_TIMEZONE') or 'America/Chicago').strip()
PICKUP_WEEKLY_SLOT_DEFINITIONS = _load_pickup_weekly_slots()
PICKUP_EVENT_TITLE = (os.environ.get('PICKUP_EVENT_TITLE') or 'SHARE Bear — Item pickup').strip()

# Video uploads (acceptance) on the quote success page
QUOTE_VIDEO_MAX_BYTES = int(os.environ.get('QUOTE_VIDEO_MAX_BYTES', str(100 * 1024 * 1024)))
# Allow large multipart bodies for short MP4s / WebM
FILE_UPLOAD_MAX_MEMORY_SIZE = min(QUOTE_VIDEO_MAX_BYTES, 100 * 1024 * 1024)
DATA_UPLOAD_MAX_MEMORY_SIZE = FILE_UPLOAD_MAX_MEMORY_SIZE

# User-facing Google appointment scheduling link for pickup booking.
GOOGLE_BOOKING_URL = os.environ.get(
    'GOOGLE_BOOKING_URL',
    'https://calendar.google.com/calendar/appointments/schedules/AcZssZ1OUNxC7H1v2XNI-xTz7-Zemzbl9TdrB60W32_29KBwPnV7QBrSzJ5LqWcwA7wAzzjRCi7ReD54?gv=true',
)
