from django.contrib import admin
from django.urls import include, path

from core.views import (
    admin_accept_quote_view,
    admin_kanban_approve_view,
    admin_kanban_assign_admin_view,
    admin_kanban_deny_view,
    admin_kanban_pickup_label_view,
    admin_kanban_pickup_view,
    admin_kanban_reset_booking_view,
    admin_kanban_take_over_view,
    admin_kanban_unapprove_view,
    admin_kanban_undeny_view,
    admin_kanban_unpickup_view,
    admin_kanban_view,
    admin_quotes_view,
    admin_video_url_view,
    ai_quote_dev_success_view,
    ai_quote_success_detail_view,
    ai_quote_view,
    home_view,
    quote_video_upload_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('ai-quote/', ai_quote_view, name='ai_quote'),
    path('ai-quote/dev-success/', ai_quote_dev_success_view, name='ai_quote_dev_success'),
    path('ai-quote/complete/<int:quote_id>/', ai_quote_success_detail_view, name='ai_quote_success_detail'),
    path('ai-quote/complete/<int:quote_id>/video/', quote_video_upload_view, name='quote_video_upload'),
    path('admin-quotes/', admin_quotes_view, name='admin_quotes'),
    path('admin-quotes/accept/<int:quote_id>/', admin_accept_quote_view, name='admin_accept_quote'),
    path('admin-dashboard/', admin_kanban_view, name='admin_kanban'),
    path('admin-dashboard/approve/<int:quote_id>/', admin_kanban_approve_view, name='admin_kanban_approve'),
    path('admin-dashboard/assign-admin/<int:quote_id>/', admin_kanban_assign_admin_view, name='admin_kanban_assign_admin'),
    path('admin-dashboard/pickup-label/<int:quote_id>/', admin_kanban_pickup_label_view, name='admin_kanban_pickup_label'),
    path('admin-dashboard/pickup/<int:quote_id>/', admin_kanban_pickup_view, name='admin_kanban_pickup'),
    path('admin-dashboard/unapprove/<int:quote_id>/', admin_kanban_unapprove_view, name='admin_kanban_unapprove'),
    path('admin-dashboard/unpickup/<int:quote_id>/', admin_kanban_unpickup_view, name='admin_kanban_unpickup'),
    path('admin-dashboard/reset-booking/<int:quote_id>/', admin_kanban_reset_booking_view, name='admin_kanban_reset_booking'),
    path('admin-dashboard/take-over/<int:user_id>/', admin_kanban_take_over_view, name='admin_kanban_take_over'),
    path('admin-dashboard/deny/<int:quote_id>/', admin_kanban_deny_view, name='admin_kanban_deny'),
    path('admin-dashboard/undeny/<int:quote_id>/', admin_kanban_undeny_view, name='admin_kanban_undeny'),
    path('admin-dashboard/video-url/<int:quote_id>/', admin_video_url_view, name='admin_video_url'),
    path('accounts/', include('users.urls')),
]
